- project:
    check:
      jobs:
        - build-ansible-collection
        - build-ansible-base
        - ansible-test-cloud-integration-vcenter_only-python36:
            vars:
              ansible_test_collections: true
            voting: false
        - ansible-test-cloud-integration-vcenter_1esxi-python36:
            vars:
              ansible_test_collections: true
            voting: false
        - ansible-test-cloud-integration-vcenter_2esxi-python36:
            vars:
              ansible_test_collections: true
            voting: false
    gate:
      jobs: []
