---
authors:
  - Ansible Network Community (ansible-network)
license_file: LICENSE
name: vmware
namespace: community
readme: README.rst
repository: https://github.com/ansible-network/ansible_collections.community.vmware
