namespace: community
name: vmware
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  community.general: '>=1.0'
repository: git@github.com:ansible-collection-migration/community.vmware.git
documentation: https://github.com/ansible-collection-migration/community.vmware/tree/master/docs
homepage: https://github.com/ansible-collection-migration/community.vmware
issues: https://github.com/ansible-collection-migration/community.vmware/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
